# LoRa concentrator configuration.
[gateway.concentrator]

# Multi spreading-factor channels (LoRa).
multi_sf_channels=[
  916600000,
  916800000,
  917000000,
  917200000,
  917400000,
  917600000,
  917800000,
  918000000,
]

# LoRa std channel (single spreading-factor).
[gateway.concentrator.lora_std]
frequency=917900000
bandwidth=250000
spreading_factor=7
