# Beacon configuration.
#
# This requires a gateway with GPS / GNSS.
[gateway.beacon]

# Compulsory RFU size.
compulsory_rfu_size=5

# Beacon frequency / frequencies (Hz).
frequencies=[
  923300000,
  923900000,
  924500000,
  925100000,
  925700000,
  926300000,
  926900000,
  927500000,
]

# Bandwidth (Hz).
bandwidth=500000

# Spreading factor.
spreading_factor=12

# TX power.
tx_power=14
