version: "3"

services:
  chirpstack:
    container_name: chirpstack
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
      - chirpstack-certificates:/etc/chirpstack/certs
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
      - API_SECRET=${API_SECRET:-you_must_change_this} # use the output of `openssl rand -base64 32`
    ports:
      - 8080:8080

  chirpstack-gateway-bridge-udp:
    container_name: chirpstack-bridge-udp
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/command/#
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-udp-ism2400:
    container_name: chirpstack-bridge-udp-ism2400
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1701:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/command/#

  chirpstack-gateway-bridge-basicstation:
    container_name: chirpstack-bridge-basicstation
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-${BAND:-eu868}.toml
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto
    environment:
      - BACKEND__BASIC_STATION__TLS_CERT=/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation.pem
      - BACKEND__BASIC_STATION__TLS_KEY=/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation-key.pem
      - BACKEND__BASIC_STATION__CA_CERT=/etc/chirpstack-gateway-bridge/certs/ca/ca.pem

  chirpstack-rest-api:
    container_name: chirpstack-api
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    container_name: chirpstack-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstack-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root

  redis:
    container_name: chirpstack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - chirpstack-redis:/data

  mosquitto:
    container_name: chirpstack-mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - chirpstack-certificates:/mosquitto/config/certs

  chirpstack-certificates:
    container_name: chirpstack-certificates
    build: 
      context: ./chirpstack-certificates
      dockerfile: Dockerfile-devel
    volumes:
      - chirpstack-certificates:/chirpstack-certificates/certs
    environment:
      - CHIRPSTACK_GATEWAY_BRIDGE_HOSTS=${CHIRPSTACK_GATEWAY_BRIDGE_HOSTS:-127.0.0.1,localhost,lns.xoseperez.com}
      - MQTT_BROKER_HOSTS=${MQTT_BROKER_HOSTS:-127.0.0.1,localhost,lns.xoseperez.com}
    command: make 

volumes:
  chirpstack-postgresql:
  chirpstack-redis:
  chirpstack-certificates:
