version: "3"

services:
  
  chirpstack:
    container_name: chirpstack
    image: chirpstack/chirpstack:4.1.1
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - chirpstack-certificates:/etc/chirpstack/certs
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - API_SECRET=$API_SECRET:-you_must_change_this}
    ports:
      - 8080:8080

  chirpstack-gateway-bridge-udp-eu868:
    container_name: chirpstack-bridge-udp-eu868
    image: chirpstack/chirpstack-gateway-bridge:4.0.3
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge.udp-eu868.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-basicstation-eu868:
    container_name: chirpstack-bridge-basicstation-eu868
    image: chirpstack/chirpstack-gateway-bridge:4.0.3
    restart: unless-stopped
    ports:
      - 3001:3001/tcp
    volumes:
      - ./configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge.basicstation-eu868.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto

  chirpstack-rest-api:
    container_name: chirpstack-api
    image: chirpstack/chirpstack-rest-api:4.1.1
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    container_name: chirpstack-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstack-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}

  redis:
    container_name: chirpstack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - chirpstack-redis:/data

  mosquitto:
    container_name: chirpstack-mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 8883:8883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - chirpstack-certificates:/mosquitto/config/certs

  chirpstack-certificates:
    container_name: chirpstack-certificates
    build: 
      context: ./chirpstack-certificates
      dockerfile: Dockerfile
    environment:
      CHIRPSTACK_GATEWAY_BRIDGE_HOSTS: ${CHIRPSTACK_GATEWAY_BRIDGE_HOSTS:-127.0.0.1,localhost}
      MQTT_BROKER_HOSTS: ${MQTT_BROKER_HOSTS:-127.0.0.1,localhost}
    volumes:
      - chirpstack-certificates:/chirpstack-certificates/certs/
    command: make

volumes:
  chirpstack-postgresql:
  chirpstack-redis:
  chirpstack-certificates:
