version: "3"

services:
  
  chirpstack:
    container_name: chirpstack
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
      - chirpstack-certificates:/etc/chirpstack/certs
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - API_SECRET=${API_SECRET:-you_must_change_this}

  chirpstack-gateway-bridge-udp:
    container_name: chirpstack-bridge-udp
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge/:/etc/chirpstack-gateway-bridge/
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=${BAND:-eu868}/gateway/{{ .GatewayID }}/command/#
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-udp.toml

  chirpstack-gateway-bridge-udp-ism2400:
    container_name: chirpstack-bridge-udp-ism2400
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1701:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge/:/etc/chirpstack-gateway-bridge/
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=ism2400/gateway/{{ .GatewayID }}/command/#
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-udp.toml

  chirpstack-gateway-bridge-basicstation:
    container_name: chirpstack-bridge-basicstation
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 3001:3001/tcp
    volumes:
      - ./configuration/chirpstack-gateway-bridge/:/etc/chirpstack-gateway-bridge/
      - chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on: 
      - mosquitto
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-${BAND:-eu868}.toml

  chirpstack-rest-api:
    container_name: chirpstack-api
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

  postgres:
    container_name: chirpstack-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstack-postgresql:/var/lib/postgresql/data
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}

  redis:
    container_name: chirpstack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - chirpstack-redis:/data
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

  mosquitto:
    container_name: chirpstack-mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 8883:8883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - chirpstack-certificates:/mosquitto/config/certs
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

  chirpstack-certificates:
    container_name: chirpstack-certificates
    build: 
      context: ./chirpstack-certificates
      dockerfile: Dockerfile
    volumes:
      - chirpstack-certificates:/chirpstack-certificates/certs/
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CHIRPSTACK_GATEWAY_BRIDGE_HOSTS=${CHIRPSTACK_GATEWAY_BRIDGE_HOSTS:-127.0.0.1,localhost}
      - MQTT_BROKER_HOSTS=${MQTT_BROKER_HOSTS:-127.0.0.1,localhost}
    command: make

volumes:
  chirpstack-postgresql:
  chirpstack-redis:
  chirpstack-certificates:
