# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="eu433/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="eu433/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="eu433/gateway/{{ .GatewayID }}/command/#"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert="/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation.pem"
  tls_key="/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation-key.pem"
  ca_cert="/etc/chirpstack-gateway-bridge/certs/ca/ca.pem"

  region="EU433"
  frequency_min=433050000
  frequency_max=434900000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      433175000,
      433375000,
      433575000,
    ]
