version: '2.4'

services:

  tailscaled:
    #image: sheng2216/tailscale:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Tailscaled
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - TS_AUTH_KEY=${TS_AUTH_KEY:-enterauthkeyhere}
    command:
      - /bin/sh
      - /launch.sh
