# LoRa concentrator configuration.
[gateway.concentrator]

# Multi spreading-factor channels (LoRa).
multi_sf_channels=[
  908700000,
  908900000,
  909100000,
  909300000,
  909500000,
  909700000,
  909900000,
  910100000,
]

# LoRa std channel (single spreading-factor).
[gateway.concentrator.lora_std]
frequency=909400000
bandwidth=500000
spreading_factor=8
