version: '3.9'

services:
    tagocore:
        container_name: tagocore
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - 8080:8888
        restart: unless-stopped
        environment:
          - TZ=${TZ:-Europe/London}
          - PUID=${PUID:-1000}
          - PGID=${PGID:-100}
