version: '3.9'

services:
    tagocore:
        container_name: tagocore
        build:
          context: ./
          dockerfile: Dockerfile
          args:
            ARCH: ${ARCH:-arm64}
            VERSION: ${VERSION:-v0.7.1}
        ports:
          - ${PORT:-8888}:8888
        restart: unless-stopped
        environment:
          - TZ=${TZ:-Europe/London}
          - PUID=${PUID:-1000}
          - PGID=${PGID:-100}
