version: "2"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=${NETWORK_SERVER__BAND__NAME:-EU868}
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - postgresql
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
    depends_on: 
      - mosquitto

  postgresql:
    #image: sheng2216/postgres_for_chirpstack:rak
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
