# LoRa concentrator configuration.
[gateway.concentrator]

# Multi spreading-factor channels (LoRa).
multi_sf_channels=[
  921400000,
  921600000,
  921800000,
  922000000,
  922200000,
  922400000,
  922600000,
  922800000,
]

# LoRa std channel (single spreading-factor).
[gateway.concentrator.lora_std]
frequency=922700000
bandwidth=250000
spreading_factor=7
