FROM alpine:edge

WORKDIR /chirpstack-certificates

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --no-cache make curl jq cfssl bash

ADD config ./config
ADD Makefile set-hosts.sh ./
RUN chmod +x set-hosts.sh && mkdir -p certs
